Repository amp-buildpacks/starknet, pull requests merged in 2024-06, with the labels that each got.

#6 Bump pipeline from 0.0.0 to 1.39.0
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/labels.yml
  .github/pipeline-version
  .github/release-drafter.yml
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
  .gitignore
  scripts/build.sh
Labels: semver:patch, type:task

#9 Fix deploy failed issue
  buildpack.toml
  go.mod
  go.sum
  scripts/build.sh
  starknet/starknet.go
Labels: type:bug, semver:major

#10 Bump Go from 1.21 to 1.22
  go.mod
  go.sum
Labels: type:task, semver:minor

#11 Bump pipeline from 1.39.0 to 1.39.0
  scripts/build.sh
Labels: semver:patch, type:task

#12 Bump Go Modules
  go.mod
Labels: semver:patch, type:task
